// Code generated by Slice Machine. DO NOT EDIT.

import CustomerLogos from './CustomerLogos/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	customer_logos: CustomerLogos,
	hero: Hero,
	rich_text: RichText
};
